### ISSUE TITLE
Pull access denied  for dukegcb/overrepresented_sequence_extract

### ISSUE THREAD

**Issue by tilschaef** [Duke-GCB/GCB-Dockerfiles#33]
I was trying to run the rna-seq pipeline when I encountered a pull access deny for dukegcb/overrepresented_sequence_extract. It does not seem to be available on Docker Hub.

Thank you in advance.

**Comment by dleehr** [comment]
@alexbarrera would you like me to set up a build for this image under the dukegcb organization? Or will you be making one elsewhere?  If there are published workflows that reference this image, we should probably just restore it in dukegcb.

**Comment by alexbarrera** [comment]
@dleehr I have updated the GGR-cwl repo with new references for a number of otherwise missing image. The missing ones have now been built and published under the [reddylab Docker Hub account](https://hub.docker.com/u/reddylab/), which is configure to run automatic builds from the [reddylab dockerfiles repo](https://github.com/ReddyLab/reddylab-dockerfiles).

@tilschaef please pull the latest changes in the GGR-cwl repo and try again.
